name: Deployment Workflow

on:
  push:
    branches:
      - Stage
      - Develop
      - Production

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build

  deploy_stage:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/stage'
    
    steps:
      - name: Deploy to Staging Environment
        run: |
          # Add your deployment script or commands here
          echo "Deploying to Staging Environment"

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: Deploy to Development Environment
        run: |
          # Add your deployment script or commands here
          echo "Deploying to Development Environment"
  

  deploy_production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/production'
    
    steps:
      - name: Deploy to Production Environment
        run: |
          # Add your deployment script or commands here
          echo "Deploying to Production Environment"
