name: Pull Request

on:
  push:
    branches:
      - Stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add more steps as needed to build, test, etc.
