name: CI/CD Pipeline

on:
  push:
    branches:
      - stage  # adjust this to match your main branch name

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          echo "Building the project..."

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]  # ensures the deploy step runs after build and test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: |
          echo "Deploying the application..."
