name: CI/CD Pipeline

on:
  push:
    branches:
      - Stage  # adjust this to match your main branch name
      - Develop
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          sudo apt-get update

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
         uname

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [Test]  # ensures the deploy step runs after build and test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: |
          exit