<<<<<<< HEAD
name: Deployment Workflow

on:
  push:
    branches:
      - Stage
      - Develop
      - Production

jobs:
  
  deploy_stage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    
    steps:
      - name: Deploy to Staging Environment
        run: echo "Deploying to Staging Environment"

  deploy_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: Deploy to Development Environment
        run: echo "Deploying to Development Environment"

  deploy_production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    
    steps:
      - name: Deploy to Production Environment
        run: echo "Deploying to Production Environment"
=======
name: hello-world

on:
  push:

jobs:
  Hello-World-from-Stage:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World..!
        run: echo "Hello world...!"
>>>>>>> 4171b57e5d0147956088c0b9f2a15ed5d809ed76
