name: CI/CD Pipeline

on:
  push:
    branches:
      - Stage  # adjust this to match your main branch name
      - Develop
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          sudo apt-get update

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
         uname
        #For Approval
      - name: Wait for approval
        if: github.event_name == 'workflow_dispatch'
        id: approval
        uses: "Aniketdk/action-automatic-approvals@v1"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          approval-comment: "Approve deployment? (Approve/Reject)"
          wait-hours: 24
          issue-number: ${{ steps.create_approval_issue.outputs.issue_number }}
   

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [Test]  # ensures the deploy step runs after build and test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: |
          exit