on:
  pull_request:
    types:
      - opened
    branches:
      - 'Stage'


jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"